<?xml version="1.0"?>
<!--
Copyright (c) 2013, Goncalo Cabrita, ISR University of Coimbra
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of Clearpath Robotics nor the
      names of its contributors may be used to endorse or promote products
      derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
-->

<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
xmlns:xacro="http://ros.org/wiki/xacro" name="mti">

    <xacro:include filename="$(find hratc2017_framework)/description/urdf/common.xacro" />

    <xacro:property name="mti_length" value="0.047" />
    <xacro:property name="mti_width" value="0.042" />
    <xacro:property name="mti_height" value="0.0135" />

    <xacro:macro name="mti" params="parent x y z rx ry rz"> 
        <link name="base_imu">
            <xacro:box_inertial x="${mti_length}"  y="${mti_width}" z="${mti_height}" mass="0.052" />
            <visual>
                <geometry>
                    <box size="${mti_length} ${mti_width} ${mti_height}"/>
                </geometry>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <material name="Black" />
            </visual>
            <collision>
                <geometry>
                    <box size="${mti_length} ${mti_width} ${mti_height}"/>
                </geometry>
            </collision>
        </link>

        <joint name="base_imu_joint" type="fixed">
            <parent link="${parent}"/>
            <child link="base_imu"/>
            <origin xyz="${x} ${y} ${z+mti_height/2}" rpy="${rx} ${ry} ${rz}" /> 
        </joint>

        <gazebo reference="base_imu">
            <material>Gazebo/Black</material>
            <turnGravityOff>false</turnGravityOff>
        </gazebo>

        <gazebo>    
            <plugin name="gazebo_ros_imu" filename="libgazebo_ros_imu.so">
                <alwaysOn>true</alwaysOn>       
                <bodyName>base_link</bodyName>
                <topicName>/imu/data</topicName>
                <serviceName>imu_service</serviceName>
                <gaussianNoise>0.0</gaussianNoise>
                <updateRate>30.0</updateRate> 
            </plugin>
        </gazebo>

    </xacro:macro>
</robot>
